### ISSUE TITLE
Firestore adapter cannot write conversation sessions 

### ISSUE THREAD

**Issue by sartoshi-foot-dao** [grammyjs/storages#118]
### Problem
Firestore cannot store conversations session data with current adapter.

### Cause
Firestore cannot encode the function definitions of the stored update objects under `log` e.g. copy, forward.

While the Admin SDK throws the error `Error: Cannot encode value: (chat_id, other, signal)`, which wasn't too informative, testing with the Web SDK produced a more useful error `Function setDoc() called with invalid data. Unsupported field value: a function`.

### Solution (?)
Perhaps the Firestore adapter should JSON.stringify / parse when writing to and reading from the database, at least for conversation sessions? It's slightly inelegant but can get the job done.

I could well be missing something very obvious, so would appreciate somebody suggesting a better approach. Thanks!

**Comment by KnorpelSenf** [comment]
Which version of the plugin are you using?

**Comment by sartoshi-foot-dao** [comment]
`"grammy": "1.9.2"`
`@grammyjs/conversations": "^1.0.2"`

Sorry, I was a little presumptuous in my original post as I am not using the officially supported Firestore adapter to save on referencing a keyfile. As my bot is hosted on GCP Cloud Functions, I use `getFirestore` from `firebase-admin/firestore`, which accesses the same service as `Firestore` from `@google-cloud/firestore`.

I adapted the official adapter to suit my approach. Here it is:

```ts
const firebaseAdapter: StorageAdapter<SessionData> = {
	read: async (key: string) => {
		const snapshot = await db.collection('sessions').doc(key).get();
		return snapshot.data() as SessionData | undefined;
	},
	write: async (key: string, value: SessionData) => {
		console.log(util.inspect(value, false, null, true /* enable colors */));
		await db
			.collection('sessions')
			.doc(key)
			.set(value);
	},
	delete: async (key: string) => {
		await db.collection('sessions').doc(key).delete();
	}
};
```

Which I then use as follows:
```ts
bot.use(
			session({
				initial() {
					return {};
				},
				storage: firebaseAdapter
			})
		);
```

I shall be more precise with future issues. Apologies for any inconveniences caused and thank you for your tireless work on this project!

**Comment by sartoshi-foot-dao** [comment]
To add as a note:

Seems like `JSON.stringify()` removes any function definitions found within the JSON. I wonder if some kind of preprocess could lint the function definitions from the conversation session data, unless they are particularly necessary for conversation replay?

**Comment by sartoshi-foot-dao** [comment]
Found a workaround without modifying official Firestore adapter with `JSON.stringify`.

Note: update dependencies to latest versions of `grammy` and `@grammyjs/conversations`.

```ts
// no need for Firestore config if using Firebase with Cloud Functions
const db = getFirestore();

// should silence Error: Value for argument is not a valid Firestore document. Cannot use "undefined" as a Firestore value
db.settings({
	ignoreUndefinedProperties: true
});
```

Problem solved.

I recognise that the [guide](https://grammy.dev/hosting/gcf.html) for Hosting on GCP is 'coming soon'. If a ancillary note on Firebase Functions would be welcome, I'd be happy to organise my learnings and document pitfalls. Any contribution guidance would be appreciated too @KnorpelSenf

**Comment by KnorpelSenf** [comment]
Great to see this solved!

@Satont this looks like a good solution. I remember doing this myself in a different project. It would be interesting to know why Google didn't set this option by default.

@sartoshi-foot-dao you're more than welcome to write this guide. I was initially planning on writing a guide for Google Cloud Functions not Firebase functions, but I guess they're using the same service internally anyway so either solution is fine for me.

Regarding website contributions, I can recommend our contribution guide: https://github.com/grammyjs/website/blob/main/CONTRIBUTING.md

Feel free to ping me or the website maintainer @roj1512 either on GitHub or on Telegram (https://t.me/grammyjs) if anything else is unclear :)

**Comment by sartoshi-foot-dao** [comment]
Thank you! I'll give it a shot tomorrow afternoon.
