### ISSUE TITLE
Property '#protocol' in type 'Collection' refers to a different member that cannot be accessed from within type 'Collection'.

### ISSUE THREAD

**Issue by Ankook** [grammyjs/storages#146]
Trying to initialize mongoDB storage
<img width="974" alt="Screenshot 2023-01-16 at 10 23 00" src="https://user-images.githubusercontent.com/52046510/212598308-e8f697fb-4892-41a9-abad-e4f9ae0a5e5f.png">

**Comment by Ankook** [comment]
i just do a copypaste from example

**Comment by Satont** [comment]
@Ankook hi. I updated all packages, can you test did it work for you now?

**Comment by Ankook** [comment]
<img width="1035" alt="Screenshot 2023-01-16 at 19 00 48" src="https://user-images.githubusercontent.com/52046510/212684925-b3266b5a-0509-47de-b382-81d3a95b93c4.png">
This works for me

**Comment by Ankook** [comment]
Yes i migrated to node. I'll check deno dependencies now.

**Comment by Ankook** [comment]
The error did not disappear after updating the packages, new dependencies lead to the same files, n
<img width="1440" alt="Screenshot 2023-01-16 at 21 23 14" src="https://user-images.githubusercontent.com/52046510/212713475-4c91a85c-7e7d-42fb-89af-31cecbd82758.png">
ew versions did not appear.

**Comment by Satont** [comment]
> The error did not disappear after updating the packages, new dependencies lead to the same files, n <img alt="Screenshot 2023-01-16 at 21 23 14" width="1440" src="https://user-images.githubusercontent.com/52046510/212713475-4c91a85c-7e7d-42fb-89af-31cecbd82758.png"> ew versions did not appear.

Upgrade `grammy_storages` to latest version, please.

**Comment by Ankook** [comment]
this error disappeared

**Comment by Ankook** [comment]
<img width="1014" alt="Screenshot 2023-01-16 at 21 59 41" src="https://user-images.githubusercontent.com/52046510/212720819-75c0f8a4-866c-48bd-b4d7-48d1e6130a11.png">

**Comment by KnorpelSenf** [comment]
Does that mean that this issue is fixed so it can be closed?

**Comment by Ankook** [comment]
Yee

пн, 16 янв. 2023 г., 22:18 KnorpelSenf ***@***.***>:

**Comment by Ankook** [comment]
Yes
