### ISSUE TITLE
[Prisma Adapter] Incompatibility with conversations plugin

### ISSUE THREAD

**Issue by IgordeOliveira** [grammyjs/storages#190]
Seems that the prisma cannot be used with the conversations plugin, look the screenshots of my code:
![image](https://github.com/grammyjs/storages/assets/19624377/976d95f3-f87f-4373-ad29-99937bbcbd68)
![image](https://github.com/grammyjs/storages/assets/19624377/25c7f380-2f5f-41cb-8872-c8c27d0cf41c)

**Comment by KnorpelSenf** [comment]
This is invalid, the storage adapter has nothing to do with the conversations plugin. You just need to add the session data type to the adapter constructor: `PrismaAdapter<SessionData>`

**Comment by roziscoding** [comment]
Closing this since an answer has been provided.
@IgordeOliveira reach out to us on the [group chat](https://t.me/grammyjs) if you are still having difficulties with this :)
