### ISSUE TITLE
How can I reset Free Storage linked to my bot token?

### ISSUE THREAD

**Issue by oluckyman** [grammyjs/storages#214]
I'm in the development stage and want to reset all the data associated with my bot token to start fresh. How can I clean up the free storage or check what it contains?

**Comment by KnorpelSenf** [comment]
So far, nobody has built an interactive dashboard for free sessions (not sure if you were asking for that). Bulk operations therefore aren't implemented yet.

You can view single session values with `console.log(ctx.session)` and you can clear session data with `ctx.session = undefined` in any handler.

**Comment by oluckyman** [comment]
thanks! these two tips are sufficient for my case.
