### ISSUE TITLE
Add TTL

### ISSUE THREAD

**Issue by Satont** [grammyjs/storages#52]
It's possible to add TTL check on read operations for all adapters.

**Comment by KnorpelSenf** [comment]
Would you want to make use of the expiry feature of storages like Redis, or rather perform the checks manually in all cases?

This may combine well with https://github.com/grammyjs/grammY/issues/188 if the latter approach is chosen.

**Comment by Satont** [comment]
> Would you want to make use of the expiry feature of storages like Redis, or rather perform the checks manually in all cases?
> 
> This may combine well with [grammyjs/grammY#188](https://github.com/grammyjs/grammY/issues/188) if the latter approach is chosen.

Only redis has expire in existed adapters as i know, so i'd like to implement it on read.

**Comment by KnorpelSenf** [comment]
I agree with that. I also think it's good to add features like that directly to the session plugin so that not every adapter has to reimplement the logic. If you think so too, we could transfer the issue to the core repo.

**Comment by Loskir** [comment]
Not relevant anymore, I suppose?

**Comment by KnorpelSenf** [comment]
> Not relevant anymore, I suppose? [grammyjs/grammY#247](https://github.com/grammyjs/grammY/issues/247)

Correct.
